config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  resources :venues do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [ :new, :create ]
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookings, only: [:destroy]
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, :end_date, presence: { message: 'must enter dates' }
  belongs_to :venue
  belongs_to :user
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :venue
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :venue
  belongs_to :user

  validates :rating, :comment, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings

  has_many :bookmarks

  has_many :venues, through: :bookings

  has_many :venues, through: :bookmarks

  has_many :venues, dependent: :destroy

  has_many :reviews
end

app/models/venue.rb
class Venue < ApplicationRecord
  validates :name, :location, :description, :capacity, :photos, :price_per_hour, presence: true
  validates :description, length: { minimum: 50 }

  has_many_attached :photos

  has_many :bookings, dependent: :destroy

  belongs_to :user

  has_many :reviews, dependent: :destroy

  has_many :bookmarks, dependent: :destroy


  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?


  include PgSearch::Model
  pg_search_scope :search_by_name_and_location,
    against: [ :name, :location ],
    using: {
      tsearch: { prefix: true }
    }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
     # For additional fields in app/views/devise/registrations/new.html.erb
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

     # For additional in app/views/devise/registrations/edit.html.erb
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
   end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  #http://localhost:3000/venues/1/bookings/new

  def index
    @user = current_user
    @bookings = @user.bookings.all
  end

  def show
    @user = User.find(params[:user_id])
    @booking = Booking.find(params[:id])
    @venue = Venue.find(@booking.venue_id)
  end


  def new
    @venue = Venue.find(params[:venue_id])
    @booking = Booking.new
  end

  def create
    @venue = Venue.find(params[:venue_id])
    @booking = Booking.new(bookings_params)
    @booking.user = current_user
    @booking.venue = @venue
    if @booking.save!
      redirect_to dashboard_path
      flash[:message] = 'Your Booking was Created Successfully!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to booking_path(@booking.venue), status: :see_other
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @venue = Venue.find(params[:venue_id])
    @user = current_user
    @bookmark = Bookmark.new
  end

  def create
    @venue = Venue.find(params[:venue_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.venue = @venue
    @bookmark.user = current_user
    if @bookmark.save!
      redirect_to venue_path(@bookmark.venue)
      flash[:message] = 'Succesfully saved venue to your dashboard!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy!
    redirect_to venue_path(@bookmark.venue)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:bookmarked)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @venues = Venue.all
  end

  def dashboard
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @venue = Venue.find(params[:venue_id])
    @review = Review.new
  end

  def create
    @venue = Venue.find(params[:venue_id])
    @review = Review.new(review_params)
    @review.venue = @venue
    @review.user = current_user
    if @review.save!
      redirect_to venue_path(@venue), notice: 'Review was successfully created.'
    else
      render 'venues/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    if params[:query].present?
      @venues = Venue.search_by_name_and_location(params[:query])
    else
      @venues = Venue.all
    end
    @markers = @venues.geocoded.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {venue: venue})
      }
    end
  end

  def show
    @venue = Venue.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    @bookmark = Bookmark.new
    @markers = [{
        lat: @venue.latitude,
        lng: @venue.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {venue: @venue})
      }]
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save
      redirect_to venue_path(@venue)
      flash[:message] = 'Your Venue was Created Successfully!'
    else
      render :new, status: :unprocessable_entity
      flash[:message] = 'Missing Fields!'
    end
  end

  private

  def venue_params
    params.require(:venue).permit(:name, :description, :location, :capacity, :price_per_hour, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_form.html.erb
<div class="column">
<%= simple_form_for [venue, booking] do |f|%>
  <div class="mb-3 form-control p-2" style="border-radius: 17px">
    <%= f.input :start_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } },
            label_html: {class:"me-3"} %>
  </div>
  <div class="mb-3 form-control p-2" style="border-radius: 17px">
    <%= f.input :end_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } },
            label_html: {class:"me-3"} %>
  </div>
  <div class="mb-3 btn-primary text-center">
  <%= f.submit 'Book', class: "btn btn-default btn-danger btn-lg", style: "color: white" %>
  </div>
<% end %>
</div>

app/views/bookings/new.html.erb
<h1> Booking page </h1>
<div class="form">
    <%= render('booking_form', booking: @booking, venue: @venue) %>
</div>

app/views/bookmarks/_bookmark_form.html.erb
 <% if user_signed_in? %>

  <% if current_user.bookmarks.select { |b| b.venue == venue }.any?  %>
    <% b = current_user.bookmarks.select { |b| b.venue == venue }.first %>
    <%= link_to bookmark_path(b), data: {turbo_method: :delete} do %>
      <div class="form-check form-switch">
        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" checked>
        <label class="form-check-label" for="flexSwitchCheckDefault"></label>
      </div>
    <% end %>
  <% else %>

        <%= simple_form_for [venue, bookmark] do |f| %>
          <div class="form-check form-switch">
          <%= f.check_box :bookmarked, class: "form-check-input", id: "bookmark", onchange: "this.form.submit()" %>
            <label class="form-check-label" for="bookmark"></label>
          </div>
          <%#= f.submit class:"btn btn-secondary"%>
        <% end %>
  <% end %>

<% end %>

app/views/bookmarks/new.html.erb
<div class="form">
    <%= render('bookmark_form', bookmark: @bookmark, venue: @venue) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venuebookr</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= favicon_link_tag asset_path('favicon-16x16.png') %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="min_height"> <%= yield %></div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_venue.html.erb
<div class="card m-3 col-3 p-1" style="width: 350px;">
  <% if venue.photos.attached? %>
    <img class="index-photo card-img-top" src=<%= cl_image_path venue.photos[0].key %> alt="Card image cap">
  <% end %>
  <div class="card-body text-start">
    <h5>🎉 <%= venue.name %></h5>
      <h6 class="card-title border-bottom border-danger pb-2"><%= venue.location %></h6>

      <p class="card-title pt-2">💰 £<%= venue.price_per_hour %> per day</p>
      <p class="card-title pt-2">👯 Capacity: <%= venue.capacity %> people</p>
      <%= link_to '', venue_path(venue), class:'stretched-link' %>

    <!-- Average Rating -->
    <div class="average-rating text-end mt-3">
      <% if venue.reviews.any? %>
        <% average_rating = venue.reviews.average(:rating).to_f %>
        <p class="mb-0">
          <% average_rating.round.times do %>
            <i class="fa-solid fa-star" style="color: #dc3545;"></i>
          <% end %>
          <%= average_rating.round %><span class="text-muted"> avg</span>
        </p>
      <% else %>
        <p class="mb-0">No reviews yet</p>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<br>
  <div class="container">
    <div class="mb-3" style="max-width: 100%; border: none;">
  <div class="card-header" style="border-bottom: 2px solid red;">
    <h5 class="fs-1"><strong> Welcome back, <%= @user.first_name.capitalize %>!</strong> </h5>
  </div>
</div>
  </div>
<div data-controller="tabs">
  <div>
    <ul class="list-inline tabs-underlined justify-content-center">
      <li>
        <a href="#" class="tab-underlined active" data-action="tabs#changeTab" data-target="tabs.tab" data-tab="1">Bookings</a>
      </li>
      <li>
        <a href="#" class="tab-underlined" data-action="tabs#changeTab" data-target="tabs.tab" data-tab="2">Your venues</a>
      </li>
      <li>
        <a href="#" class="tab-underlined" data-action="tabs#changeTab" data-target="tabs.tab" data-tab="3">Bookmarked venues</a>
      </li>
    </ul>
  </div>

  <div class="container" data-target="tabs.content" data-tab="1">
    <br>
    <div class="border-bottom border-danger pb-2">
      <h1>Your Bookings</h1>
    </div>
    <br>
      <div class="row justify-content-center">
        <% @user.bookings.each do |booking| %>
          <%= link_to venue_path(booking.venue), class: "card m-3 col-3 p-2", style: "width: 18rem;" do %>
            <div>
              <img src=<%= cl_image_path booking.venue.photos[0].key %> class="index-photo card-img-top" alt="booking-photo">
              <div class="card-body">
                <h5 class="card-title border-bottom border-danger pb-2"><%= booking.venue.name %></h5>
                <h5 class="card-title pb-2"><%= (booking.end_date - booking.start_date).to_i %> Nights x £<%= booking.venue.price_per_hour %></h5>
                <h5 class="card-title border-bottom border-danger pb-2">Total Price: £ <%= "#{ (booking.end_date - booking.start_date).to_i * booking.venue.price_per_hour}" %></h5>
                <h5 class="card-title">From <%= booking.start_date.to_formatted_s(:long_ordinal) %> to <%= booking.end_date.to_formatted_s(:long_ordinal) %></h5>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>

  <div class="container d-none" data-target="tabs.content" data-tab="3">
    <br>
    <div class="border-bottom border-danger pb-2">
      <h1>Your Bookmarks</h1>
    </div>
    <br>
      <div class="row justify-content-center">
        <% @user.bookmarks.each do |bookmark| %>
        <div class="card m-3 col-3 p-2" style="width: 18rem;">
            <% if bookmark.venue.photos.attached? %>
              <img class="index-photo card-img-top rounded" src=<%= cl_image_path bookmark.venue.photos[0].key %> alt="Card image cap">
            <% end %>
              <div class="card-body">
              <h5 class="card-title border-bottom border-danger pb-2"><%= bookmark.venue.name %></h5>
                <h5 class="card-title pt-2"> £<%= bookmark.venue.price_per_hour %> per day</h5>
            <%= link_to '', venue_path(bookmark.venue), class:'stretched-link' %>
            </div>
          </div>
      <% end  %>
  </div>
  </div>


  <div class="container d-none" data-target="tabs.content" data-tab="2">
    <br>
    <div class="border-bottom border-danger pb-2">
      <h1>Your Venues</h1>
    </div>


    <br>
      <div class="row justify-content-center">
        <% @user.venues.each do |venue| %>
          <div class="card m-3 col-3 p-2" style="width: 18rem;">
            <% if venue.photos.attached? %>
              <img class="index-photo card-img-top rounded" src=<%= cl_image_path venue.photos[0].key %> alt="Card image cap">
            <% end %>
              <div class="card-body">
              <h5 class="card-title border-bottom border-danger pb-2"><%= venue.name %></h5>
                <h5 class="card-title pt-2"> £<%= venue.price_per_hour %> per day</h5>
            <%= link_to '', venue_path(venue), class:'stretched-link' %>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

<%= render "shared/flash" %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://drinkohza.com/cdn/shop/articles/pexels-cottonbro-3171815.jpg?v=1633625938);">
  <div class="container mx-5 my-5 row justify-content-center">
    <h1 style="font-size: 50px"> <strong> Find the perfect venue for your next celebration. </strong></h1>
    <p class="mt-2">Create memories. Celebrate in style. </p>
  <div >
  <div class="col-sm-4 my-1">
    <%= form_with url: venues_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by venue name or location"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-danger", style: "color: white; text-decoration: none;" %>
    <% end %>
  </div>
</div>

  </div>
</div>
<br>
<br>

  <div class="container text-center text-danger mb-5">
    <h1 style="font-size: 40px">
        Big, small, outdoors, or indoors –
        <u><em><a href="/venues" style="text-decoration: none; color: inherit;">find the one for you</a></em></u>
    </h1>
</div>

  <div class = "info-banner d-flex justify-content-center">
    <div class= "d-flex justify-content-center mx-5 fa-solid fa-user">
      <h5>Trusted by 50,000+ customer</h5>
    </div>
    <div class= "d-flex justify-content-center mx-5 fa-solid fa-circle-check">
      <h5> Your celebration, our commitment </h5>
    </div>
    <div class= "d-flex justify-content-center mx-5 fa-solid fa-star">
      <h5> 4.7 out of 5 - Trustpilot </h5>
      </div>
  </div>

    <div class="container ml-5 mt-5">
            <h1 style="font-size: 40px">Find the perfect venue for you</h1>
    </div>

  <div class="container">
    <div class="cards justify-content-center">
      <% @venues.each do |venue| %>
        <%= render "venue", venue: venue %>
      <% end %>
    </div>
  </div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@venue, @review] do |f| %>
  <div class="form-group">

    <%= f.input :rating, as: :select, collection: 1..5, include_blank: false, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group" >

    <%= f.input :comment, as: :text, placeholder: "How was your experience at #{@venue.name}?", input_html: { class: "form-control", rows: 4 } %>
  </div>

  <%= f.button :submit, class: "btn btn-danger", style: "border-radius: 10px; color: white; margin-top: 10px;" %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="alert alert-success" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer m-3">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> at VenueBookr
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3 sticky-top">
  <div class="d-flex align-items-center">
    <%= link_to root_path, style: "text-decoration: none; color: inherit;" do %>
      <h3 class="d-flex align-items-center">
        <%= image_tag "logo_red.png", alt: "alttext", class: "logo mr-2" %>
        <span class="venuebookr-text fw-bold">VenueBookr</span>
      </h3>
    <% end %>
  </div>

  <div>
    <div class="col-sm-12 my-1 mx-5">
      <% unless params[:controller] == "pages" && params[:action] == "home" %>
        <%= form_with url: venues_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search by venue name or location"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-danger", style: "color: white; text-decoration: none;" %>
        <% end %>
      <% end %>
    </div>
  </div>



  <ul class="nav navbar-right">
    <li>
      <button class="btn btn-form btn-small">
        <% if user_signed_in? %>
          <%= link_to "Become a host", new_venue_path, style: "color: red; text-decoration: none; margin-right: 10px;" %>
        <% else%>
          <%= link_to "Become a host", new_user_session_path, style: "color: red; text-decoration: none; margin-right: 10px;" %>
        <% end %>
      </button>
    </li>

    <% if !user_signed_in? %>
      <li class="btn btn-danger mx-1"><%= link_to "Log in", new_user_session_path, style: "color: white; text-decoration: none;" %></li>
      <li class="btn btn-secondary"><%= link_to "Sign Up", new_user_registration_path, style: "color: white; text-decoration: none;" %></li>
    <% else %>
      <div class="dropdown">
        <a href="#" id="userDropdown" data-bs-toggle="dropdown">
          <%= image_tag('avatar.png', alt: 'Your Image Alt Text', style: 'width: 40px; height: 40px; margin-left: 10px; margin-right: 10px;') %>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown" data-controller="tabs">
          <li>
            <%= link_to dashboard_path(current_user) do %>
            <i class="fa-solid fa-gauge" style="color: #dc3545;"></i>
          Dashboard
          <% end %>
          </li>

          <li class="divider"></li>

          <li>
            <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
            <i class="fa-solid fa-arrow-right-from-bracket" style="color: #dc3545;"></i>
            Sign out
          <% end %>
          </li>
        </ul>
      </div>

    <% end %>
  </ul>
</div>

app/views/venues/_form.html.erb
<div class="column">
<%= simple_form_for(venue) do |f|%>
  <div class="mb-3 form-control">
    <%= f.input :name, input_html: { class:"form-control bg-white"} %>
  </div>
  <div class="mb-3 form-control">
    <%= f.input :description, input_html: { class:"form-control bg-white"} %>
  </div>
  <div class="mb-3 form-control">
    <%= f.input :location,
      input_html: {data: {address_autocomplete_target: "location"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
  </div>
  <div class="mb-3 form-control">
    <%= f.input :capacity, input_html: { class:"form-control bg-white"} %>
  </div>
  <div class="mb-3 form-control">
    <%= f.input :price_per_hour, label: "Price per day" , input_html: { class:"form-control bg-white"} %>
  </div>
  <div class="mb-3 form-control">
  <%= f.input :photos, as: :file, input_html: { multiple: true, class:"form-control"} %>
  </div>
  <div class="mb-3 btn-primary text-center">
  <%= f.submit 'Create venue', class: "btn btn-default btn-danger", style: "color: white"%>
  </div>
<% end %>
</div>

app/views/venues/_info_window.html.erb
<div class="border border-danger rounded">
<img class="index-photo card-img-top rounded h-50" src=<%= cl_image_path venue.photos[0].key %> alt="Card image cap">
<h5><%= venue.name %></h5>
<h6><%= venue.location %></h6>
<%= link_to '', venue_path(venue), class:'stretched-link' %>
</div>

app/views/venues/_venue.html.erb
<div class="card m-3 col-lg-5 col-md-2 p-2 text-center">
    <% if venue.photos.attached? %>
      <img class="index-photo card-img-top rounded" src=<%= cl_image_path venue.photos[0].key %> alt="Card image cap" id="index-photo">
    <% end %>
    <div class="card-body">
      <h5>🎉 <%= venue.name %></h5>
      <h6 class="card-title border-bottom border-danger pb-2"><%= venue.location %></h6>

      <p class="card-title pt-2">💰 £<%= venue.price_per_hour %> per day</p>
      <p class="card-title pt-2">👯 Capacity: <%= venue.capacity %> people</p>
      <%= link_to '', venue_path(venue), class:'stretched-link' %>
    </div>
  </div>

app/views/venues/index.html.erb
<div class="container">
  <div>
  <h1>All venues</h1>
  </div>
    <div class="row">
      <div class="row col-md-8 col-lg-7 mt-3">
        <% @venues.each do |venue| %>
          <%= render "venue", venue: venue %>
        <% end %>
      </div>
      <div class="col-md-4 col-lg-5 mt-3">
        <div style="width: 100%; height: 600px;"
            id="index-map"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
</div>

app/views/venues/new.html.erb
<div class="container col-6">
<div>
  <h1 class="mt-4 text-center">Add a new venue</h1>
    <%= render 'form', venue: @venue %>
  <p class="mt-3 text-center"><%= link_to "Back to venues", venues_path %></p>
</div>
</div>